# Generated by Django 2.0.2 on 2018-06-05 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comic', '0002_auto_20180527_1936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_id',
            new_name='book_url',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='chapter_id',
            new_name='chapter_url',
        ),
    ]
